spring.application.name=EnterpriseIntegration14Patterns
spring.activemq.broker-url=vm://localhost
spring.activemq.in-memory=true
spring.activemq.packages.trust-all=true
iris.api.url=http://192.168.1.14:8080/irf-provider-container/api/v3.0.0/party/customers