spring.application.name=ApacheCamelEg2_RestToQueue
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

spring.jms.pub-sub-domain=false
camel.rest.component=platform-http
camel.rest.binding-mode=off
camel.servlet.mapping.context-path=/api/*
